"""
Feature Testing Framework — HTML Report Generator

Reads pytest's JSON report (produced by pytest-json-report) and generates
a simple, non-technical HTML report designed for non-technical stakeholders.

Usage (called automatically by pytest via conftest hook, or manually):

    python reporting/generate_report.py --input .report.json --output reporting/output/report.html

The report shows:
  - Overall PASS / FAIL summary
  - Per-feature results with pass-rate per test
  - Per-run PASS/FAIL verdicts and reasons for failed tests (drill-down)
  - Run metadata (date, model, N_RUNS, threshold)
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# HTML templates
# ---------------------------------------------------------------------------

_HTML_PAGE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Feature Test Report — {report_date}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #f5f7fa; color: #333; padding: 24px; }}
    h1 {{ font-size: 1.6rem; margin-bottom: 4px; color: #1a1a2e; }}
    .meta {{ font-size: 0.85rem; color: #666; margin-bottom: 24px; }}
    .summary-box {{ display: flex; align-items: center; gap: 16px;
                    background: white; border-radius: 10px; padding: 20px 28px;
                    box-shadow: 0 2px 8px rgba(0,0,0,.07); margin-bottom: 28px; }}
    .summary-icon {{ font-size: 2.4rem; }}
    .summary-text {{ font-size: 1.2rem; font-weight: 600; }}
    .summary-count {{ font-size: 0.95rem; color: #555; }}
    .feature-block {{ background: white; border-radius: 10px;
                      box-shadow: 0 2px 8px rgba(0,0,0,.07); margin-bottom: 20px;
                      overflow: hidden; }}
    .feature-header {{ padding: 14px 20px; font-weight: 600; font-size: 1rem;
                       border-bottom: 1px solid #eee; background: #fafbfc; }}
    .test-row {{ display: flex; align-items: flex-start; gap: 12px;
                 padding: 12px 20px; border-bottom: 1px solid #f0f0f0; }}
    .test-row:last-child {{ border-bottom: none; }}
    .badge {{ flex-shrink: 0; width: 28px; text-align: center; font-size: 1.1rem; }}
    .test-name {{ font-size: 0.9rem; font-weight: 500; flex: 1; }}
    .run-rate {{ font-size: 0.82rem; color: #888; margin-top: 2px; }}
    .fail-detail {{ margin-top: 8px; background: #fff5f5; border-left: 3px solid #e74c3c;
                    border-radius: 4px; padding: 8px 12px; font-size: 0.82rem; color: #555; }}
    .run-line {{ margin: 2px 0; }}
    .run-pass {{ color: #27ae60; }}
    .run-fail {{ color: #e74c3c; }}
    details summary {{ cursor: pointer; color: #888; font-size: 0.8rem; margin-top: 12px; }}
    .adv-table {{ width: 100%; border-collapse: collapse; font-size: 0.82rem; margin-top: 8px; }}
    .adv-table th, .adv-table td {{ text-align: left; padding: 4px 8px;
                                    border-bottom: 1px solid #eee; }}
    .adv-table th {{ font-weight: 600; color: #555; }}
    footer {{ text-align: center; font-size: 0.78rem; color: #aaa; margin-top: 32px; }}
  </style>
</head>
<body>
  <h1>🎓 Dialog System — Feature Test Report</h1>
  <p class="meta">Run date: <strong>{report_date}</strong> &nbsp;·&nbsp;
                  Model: <strong>{model}</strong> &nbsp;·&nbsp;
                  Runs per test: <strong>{n_runs}</strong> &nbsp;·&nbsp;
                  Pass threshold: <strong>{threshold_pct}%</strong></p>

  <div class="summary-box">
    <span class="summary-icon">{overall_icon}</span>
    <div>
      <div class="summary-text">Overall Result: {overall_label}</div>
      <div class="summary-count">{passed_tests} of {total_tests} test groups passed</div>
    </div>
  </div>

  {feature_blocks}

  <details>
    <summary>Advanced details (run configuration)</summary>
    <table class="adv-table" style="margin-top:8px;">
      <tr><th>Setting</th><th>Value</th></tr>
      <tr><td>N_RUNS</td><td>{n_runs}</td></tr>
      <tr><td>PASS_THRESHOLD</td><td>{threshold_pct}%</td></tr>
      <tr><td>System model</td><td>{model}</td></tr>
      <tr><td>Report generated</td><td>{report_date}</td></tr>
    </table>
  </details>

  <footer>Generated by the Lingolino Feature Testing Framework</footer>
</body>
</html>"""

_FEATURE_BLOCK = """\
<div class="feature-block">
  <div class="feature-header">{feature_name}</div>
  {test_rows}
</div>"""

_TEST_ROW_PASS = """\
<div class="test-row">
  <span class="badge">✅</span>
  <div>
    <div class="test-name">{test_label}</div>
    <div class="run-rate">{run_rate}</div>
  </div>
</div>"""

_TEST_ROW_FAIL = """\
<div class="test-row">
  <span class="badge">❌</span>
  <div>
    <div class="test-name">{test_label}</div>
    <div class="run-rate">{run_rate}</div>
    <div class="fail-detail">
      <strong>Failure detail:</strong><br/>
      {fail_lines}
    </div>
  </div>
</div>"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _test_label(node_id: str) -> str:
    """Convert a pytest node ID into a readable label for non-technical readers."""
    # e.g. "child-name-and-gender/test_name_usage.py::TestNameUsageFixtureBased::test_name_used_female_child"
    parts = node_id.split("::")
    # Last part is the test function name
    func = parts[-1] if parts else node_id
    # Convert snake_case to sentence-like label
    label = func.replace("test_", "").replace("_", " ").capitalize()
    return label


def _feature_name(node_id: str) -> str:
    """Extract feature directory name and humanise it."""
    # node_id starts with something like "agentic-system/feature-testing/child-name-and-gender/..."
    parts = node_id.replace("\\", "/").split("/")
    # Find the part after "feature-testing"
    try:
        idx = next(i for i, p in enumerate(parts) if p == "feature-testing")
        raw = parts[idx + 1] if idx + 1 < len(parts) else "Unknown Feature"
    except StopIteration:
        raw = parts[0] if parts else "Unknown Feature"
    return raw.replace("-", " ").title()


def _extract_run_details(longrepr: str) -> tuple[str, list[tuple[bool, str]]]:
    """
    Parse run-level PASS/FAIL lines from an AssertionError longrepr.

    Expected format produced by run_n_times():
        Only X/N runs passed (required: Y%)
          Run 1: PASS — ...
          Run 2: FAIL — reason text
    """
    runs: list[tuple[bool, str]] = []
    summary = ""
    for line in longrepr.splitlines():
        line = line.strip()
        m = re.match(r"Run\s+(\d+):\s+(PASS|FAIL)\s*[—–-]\s*(.*)", line, re.IGNORECASE)
        if m:
            runs.append((m.group(2).upper() == "PASS", m.group(3)))
        elif "runs passed" in line.lower():
            summary = line
    return summary, runs


def _parse_run_rate(longrepr: str) -> str:
    """Extract 'X/N runs passed' summary from longrepr."""
    for line in longrepr.splitlines():
        if "runs passed" in line.lower():
            return line.strip()
    return ""

# ---------------------------------------------------------------------------
# Core report builder
# ---------------------------------------------------------------------------

def build_report(json_path: Path, output_path: Path, n_runs: int, threshold: float, model: str) -> None:
    """Read pytest JSON report and write an HTML report."""
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    tests = data.get("tests", [])
    report_date = datetime.now().strftime("%Y-%m-%d %H:%M")
    threshold_pct = int(threshold * 100)

    # Group tests by feature
    from collections import defaultdict
    feature_groups: dict[str, list[dict]] = defaultdict(list)
    for t in tests:
        node_id = t.get("nodeid", "")
        fname = _feature_name(node_id)
        feature_groups[fname].append(t)

    passed_tests = 0
    total_tests = len(tests)
    feature_html_parts: list[str] = []

    for feature, group in feature_groups.items():
        rows_html: list[str] = []
        for t in group:
            outcome = t.get("outcome", "failed")
            node_id = t.get("nodeid", "")
            label = _test_label(node_id)
            longrepr = ""
            if outcome == "failed":
                call = t.get("call", {})
                longrepr = call.get("longrepr", "") if isinstance(call, dict) else str(call)

            if outcome == "passed":
                passed_tests += 1
                rows_html.append(
                    _TEST_ROW_PASS.format(
                        test_label=label,
                        run_rate="All runs passed ✓",
                    )
                )
            else:
                run_summary, run_details = _extract_run_details(longrepr)
                run_rate = run_summary or "Failed"

                if run_details:
                    fail_lines_html = "<br/>".join(
                        f'<span class="{"run-pass" if p else "run-fail"}">'
                        f'Run {i+1}: {"PASS" if p else "FAIL"} — {r}</span>'
                        for i, (p, r) in enumerate(run_details)
                    )
                else:
                    # Contract test or unexpected failure — show raw longrepr truncated
                    snippet = longrepr[:300].replace("<", "&lt;").replace(">", "&gt;")
                    fail_lines_html = f'<span class="run-fail">{snippet}</span>'

                rows_html.append(
                    _TEST_ROW_FAIL.format(
                        test_label=label,
                        run_rate=run_rate,
                        fail_lines=fail_lines_html,
                    )
                )

        feature_html_parts.append(
            _FEATURE_BLOCK.format(
                feature_name=feature,
                test_rows="\n".join(rows_html),
            )
        )

    overall_pass = passed_tests == total_tests
    overall_icon = "✅" if overall_pass else "❌"
    overall_label = "PASSED" if overall_pass else "FAILED"

    html = _HTML_PAGE.format(
        report_date=report_date,
        model=model,
        n_runs=n_runs,
        threshold_pct=threshold_pct,
        overall_icon=overall_icon,
        overall_label=overall_label,
        passed_tests=passed_tests,
        total_tests=total_tests,
        feature_blocks="\n".join(feature_html_parts),
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"✅ HTML report written to: {output_path}")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate HTML feature test report.")
    parser.add_argument("--input", required=True, help="Path to pytest JSON report (.report.json)")
    parser.add_argument("--output", default="reporting/output/report.html", help="Output HTML file path")
    parser.add_argument("--n-runs", type=int, default=5, help="N_RUNS used in the test run")
    parser.add_argument("--pass-threshold", type=float, default=0.80, help="Pass threshold used (0.0–1.0)")
    parser.add_argument("--model", default="gemini-2.0-flash", help="Model name used")
    args = parser.parse_args()

    build_report(
        json_path=Path(args.input),
        output_path=Path(args.output),
        n_runs=args.n_runs,
        threshold=args.pass_threshold,
        model=args.model,
    )


if __name__ == "__main__":
    main()

